### ISSUE TITLE
Admin UI is not showing latest strategy parameters updated via API

### ISSUE THREAD

**Issue by TimNZ** [Unleash/unleash#494] opened 2019-09-15 20:50 UTC
I'm updating feature toggle strategy parameters via the Admin API and the UI is not displaying updated values even though it is retrieving the updated data.

Note that '3781' you can see in DevTools response is not displayed in the UI list.

<img width="1769" alt="Screen Shot 2019-09-16 at 8 45 29 AM" src="https://user-images.githubusercontent.com/1051701/64927399-9e8bd380-d85e-11e9-8969-18f349efa21f.png">

**Comment by ivarconr** [comment] 2019-09-16 05:00
That's because the UI is using a temp store while editing. Should work if you close the edit view and reopen.

**Comment by TimNZ** [comment] 2019-09-16 05:06
I am navigating all over the place and come back to the Edit view and still showing old values.
Only way to update is to reload the page.

**Comment by TimNZ** [comment] 2019-09-16 05:12
Ok, got to explicitly click Cancel.
Is this intended? It's not intuitive.

**Comment by ivarconr** [comment] 2019-09-16 06:14
It could be improved. Probably indicating that there is a diff with the server version.

**Comment by ivarconr** [comment] 2019-09-16 07:55
@TimNZ How should it work for it be intuitive for the user and avoid the user loosing data? The idea have been that the user should be allowed to change strategies without saving as she might not want to update clients before finished changing strategies. 

The problem is that update might cause a conflict, and this is not handled well today (last write wins)

**Comment by TimNZ** [comment] 2019-09-16 18:32
@ivarconr, it's not a standard UX.
Usually you switch away from a view in an app and come back, you get latest data.

Since you have the refreshed features state, how about a visual indicator saying this feature toggle has been modified elsewhere when you detect a difference, and click Refresh, or Update could override other changes?

If I'm the only one bringing it up, it's unlikely to be a major issue, I'm just being pedantic. 🤪
I've got no idea how Unleash UI vs API is used in the real world.

**Comment by ivarconr** [comment] 2020-12-15 12:57
fixed in unleash `3.8.2`. Unleash will now always fetch updated toggle state from server when entering the "edit section". In addition we plan to keep it always in sync as soon as we have landed the push support, discussions started in #383

**Closed by ivarconr** 2020-12-15 12:57 UTC
