### ISSUE TITLE
Sql server support

### ISSUE THREAD

**Issue by LarsAndreasEk** [Unleash/unleash#399] opened 2019-03-07 10:41 UTC
Hi,

We consider using Unleash on a project, but operationally postgresql seems to be a blocker for us. Is there any way to get Sql Server support into the product? Will you accept such a pull request. for instance?

**Comment by ivarconr** [comment] 2019-03-07 19:24
My plan is to make the database layer more plug-able so that it is possible to provide custom database implementations. This will require a few design changes and a clearly defined interface with proper validation and tests. 

I have a few other projects on my plate before I can start that process. I always enjoy having people contributing, sharing and contributing is key! I do however believe a proper database-abstraction is required to make this happen.  

Closing this is a duplicate of https://github.com/Unleash/unleash/issues/316.

**Closed by ivarconr** 2019-03-07 19:24 UTC
