### ISSUE TITLE
Feature toggle description has word-break: break-all instead of break-word

### ISSUE THREAD

**Issue by elmaxe** [Unleash/unleash#4030] opened 2023-06-21 09:03 UTC
### Describe the bug

The feature toggle description in the feature toggle breaks words in the middle of the word instead of per word. See an example image below.

The following text: `Whimsy kumquat scurried giggleplex beneath zephyr truffle thundersnow. Flutterpickle moonbeam wrigglesnort wibblewobble squigglejuice inquisipuddle.`
is wrapped as follows:

```
Whimsy kumquat scurried giggle
plex beneath zephyr truffle thunder
snow. Flutterpickle moonbeam
wrigglesnort wibblewobble squig
glejuice inquisipuddle.
```
instead of
```
Whimsy kumquat scurried 
giggleplex beneath zephyr truffle 
thundersnow. Flutterpickle
moonbeam wrigglesnort
wibblewobble squigglejuice
inquisipuddle.
```

![image](https://github.com/Unleash/unleash/assets/33149910/7f8d3829-c3b8-4ffd-871b-b5e617ed9b83)

Suggested solution: set `word-break: break-word`

### Expected behavior

Word break should be per word, not in the middle of words

### Screenshots

![image](https://github.com/Unleash/unleash/assets/33149910/7f8d3829-c3b8-4ffd-871b-b5e617ed9b83)

### Unleash version

5.1.8

### Subscription type

Pro

### Hosting type

Hosted by Unleash

**Comment by Tymek** [comment] 2023-06-22 06:48
Duplicate of https://github.com/Unleash/unleash/issues/3096
I'll solve it this week, unless you'd like to give it a go.

**Closed by Tymek** 2023-06-22 06:48 UTC
Labels: bug
