### ISSUE TITLE
Updating multiple feature toggles at once using the API

### ISSUE THREAD

**Issue by saidfarah** [Unleash/unleash#1695] opened 2022-06-09 15:57 UTC
### Describe the bug

I cannot seem to update multiple feature toggles using the API. I can only do them manually.

The objective I'm trying to achieve is to back-up and restore feature toggles to be rolled back in case of an error/issue. I'm using python to pull in all feature toggles in json format and store them in a bucket in GCP for the back-up. For the restore I'm also using python to pull the json file from the bucket, filter it and pass it in the request.put method in python.

When I ran requests.post it only created the feature toggles. It didn't include the description, enabled, stale, type fields. So I only have around 40 toggles with only their names configured.

### Steps to reproduce the bug

```
API_KEY = ""
server = "http://localhost:4242/api/"

headers = {
    "Authorization": f"{API_KEY}",
    "Content-Type": "application/json"
    }

with open('./test.json') as file:
    data = json.load(file)

for i in data['features']:
    toggles = {
        "name": i['name'],
        "description:": i['description'],
        "enabled:": i['enabled'],
        "stale:": i['stale'],
        "type:": i['type']
    }

    url = server + f"admin/projects/default/features/{i['name']}"
    r = requests.put(url=url, headers=headers, json=toggles)
    print(r.status_code)
```

### Expected behavior

Supposed to update feature toggles with description, enabled, stale and type.

### Unleash version

latest

**Comment by thomasheartman** [comment] 2022-06-10 09:09
Hey, @saidfarah! Thanks for the issue 😄 

> The objective I'm trying to achieve is to back-up and restore feature toggles to be rolled back in case of an error/issue.

If what you want to do is to back up and restore toggles, have you had a look at [Unleash's import/export api](https://docs.getunleash.io/deploy/import_export)? If I understand your use case, that API should cover your needs pretty well (and with much less manual work to boot!). Would that solve your issue?

> When I ran requests.post it only created the feature toggles. It didn't include the description, enabled, stale, type fields. So I only have around 40 toggles with only their names configured.

That sounds strange. Just to double check: did you PUT or POST them? PUT shouldn't allow you to create toggles that don't exist. POST should create toggles just fine. I just tested on against an instance on version 4.12.5 and it works as expected. Which version of Unleash are you using?

**Comment by saidfarah** [comment] 2022-06-10 09:45
> Hey, @saidfarah! Thanks for the issue 😄
> 
> > The objective I'm trying to achieve is to back-up and restore feature toggles to be rolled back in case of an error/issue.
> 
> If what you want to do is to back up and restore toggles, have you had a look at [Unleash's import/export api](https://docs.getunleash.io/deploy/import_export)? If I understand your use case, that API should cover your needs pretty well (and with much less manual work to boot!). Would that solve your issue?
> 
Thanks. Will look into this now.
> > When I ran requests.post it only created the feature toggles. It didn't include the description, enabled, stale, type fields. So I only have around 40 toggles with only their names configured.
> 
> That sounds strange. Just to double check: did you PUT or POST them? PUT shouldn't allow you to create toggles that don't exist. POST should create toggles just fine. I just tested on against an instance on version 4.12.5 and it works as expected. Which version of Unleash are you using?

When I initially created the toggles I used the POST method. I tried to update using the PUT method. POST just created the toggles with only their names configured. PUT doesn't add in the description or other fields etc... I'm also using 4.12.5.

**Comment by thomasheartman** [comment] 2022-06-10 10:07
> Thanks. Will look into this now.

Great! Let me know whether it covers your needs or not ☺️ 

> When I initially created the toggles I used the POST method. I tried to update using the PUT method. POST just created the toggles with only their names configured. PUT doesn't add in the description or other fields etc... I'm also using 4.12.5

Huh, that is very strange. Can you reproduce that with a simple curl request for one toggle?

**Comment by saidfarah** [comment] 2022-06-10 12:01
Ok, I'm now using the import endpoint. I've tried running these 2 scripts and here are the results.

**SCRIPT 1**
```
import requests
from google.cloud import storage
import json
from dotenv import load_dotenv
import os
from datetime import datetime
load_dotenv()

now = datetime.now().strftime("%d-%m-%y")
bucket_name = "development-unleash-backups"

client = storage.Client.from_service_account_json("unleash-dev.json")
bucket = client.get_bucket('development-unleash-backups')
blob = bucket.get_blob(f"unleash-backup-{now}.json")
file_data = json.loads(blob.download_as_string())


API_KEY = ""

server = "http://localhost:4242"
url = server + "/api/admin/state/import"

headers = {
    "Authorization": f"{API_KEY}",
    "Content-Type": "application/json",
    "keep": "false"
    }

r = requests.post(url=url, headers=headers, json=file_data)
print(r.status_code)
print(r.raise_for_status())
```

This returns a 202 but doesn't update any of the present toggles with anything other than their names.


**SCRIPT 2**

```
import requests
from google.cloud import storage
import json
from dotenv import load_dotenv
import os
from datetime import datetime
load_dotenv()

now = datetime.now().strftime("%d-%m-%y")
bucket_name = "development-unleash-backups"

client = storage.Client.from_service_account_json("unleash-dev.json")
bucket = client.get_bucket('development-unleash-backups')
blob = bucket.get_blob(f"unleash-backup-{now}.json")
file_data = json.loads(blob.download_as_string())


API_KEY = ""
server = "http://localhost:4242"

headers = {
    "Authorization": f"{API_KEY}",
    "Content-Type": "application/json"
    }
for i in file_data['features']:
    toggles = {
        "name": i['name'],
        "description:": i['description'],
        "type:": i['type'],
        "project:": i['project'],
        "stale:": i['stale']
    }

    url = server + "/api/admin/state/import"
    r = requests.post(url=url, headers=headers, json=toggles)
    print(r.status_code)
    print(r.raise_for_status())
```

This returns a 400

**Comment by thomasheartman** [comment] 2022-06-13 09:17
> The goal is to have daily back-ups exported to a bucket in GCP. For some instance, say something has changed and we want to restore to the previous state the day before, a script will fetch the json for the day before and import it, overwriting all existing toggles and creating new ones if they weren't already present.

Got it! Would you also want to remove toggles that didn't exist before? If so, then using drop=true might actually be what you're looking for. Just keep in mind that it will also remove any existing API keys until the changes introduced in #1668 are released.

> When I set keep=false I also get a 400.

That sounds very strange. You did that as a query parameter, right? Could you show me the exact request?

**Comment by saidfarah** [comment] 2022-06-13 10:52
> > When I set keep=false I also get a 400.
> 
> That sounds very strange. You did that as a query parameter, right? Could you show me the exact request?

**REQUEST**

```
import requests
from google.cloud import storage
import json
from dotenv import load_dotenv
import os
from datetime import datetime
load_dotenv()
import logging

try:
    import http.client as http_client
except ImportError:
    # Python 2
    import httplib as http_client
http_client.HTTPConnection.debuglevel = 1

logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

now = datetime.now().strftime("%d-%m-%y")
bucket_name = "development-unleash-backups"

client = storage.Client.from_service_account_json("restore/unleash-dev.json")
bucket = client.get_bucket('development-unleash-backups')
blob = bucket.get_blob(f"unleash-backup-{now}.json")
file_data = json.loads(blob.download_as_string())


API_KEY = ""

server = "http://localhost:4242"
url = server + "/api/admin/state/import"

headers = {
    "Authorization": f"{API_KEY}",
    "Content-Type": "application/json"
    }

parameters = {
    "keep": "false"
}

r = requests.post(url=url, headers=headers, json=file_data, params=parameters)
```

**RESPONSE (with verbose logging enabled)**

```
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Content-Type: application/json; charset=utf-8
header: ETag: W/"2526-jNvAYQlgdQAyDlc7ZmMytlyYg+g"
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: Date: Mon, 13 Jun 2022 10:50:40 GMT
header: Connection: keep-alive
header: Keep-Alive: timeout=60
header: Transfer-Encoding: chunked
DEBUG:urllib3.connectionpool:http://localhost:4242 "POST /api/admin/state/import?keep=false HTTP/1.1" 400 None
```

**Comment by thomasheartman** [comment] 2022-06-14 14:19
Huh, I can't really make heads or tails of that. I'm probably missing something, but as far as I can tell, that should work. 

Regardless of that one request: we've been doing some digging on our side, and it seems like something is not working as I had expected, at least. We've got a sesh about it tomorrow, so I'll come back to you with more details after that, if that's alright? ☺️

**Comment by saidfarah** [comment] 2022-06-15 12:36
Unfortunately it still doesn't work.

For example, I've ran the script which pulls in the info of this toggle below.
```
{'name': 'p1fd.users.write.only.p2', 'description:': '(Used by User Aggregation to stop writing to P1)\nfalse means Aggregation writes to P1 and P2\ntrue means Aggregation writes ONLY to P2', 'enabled:': False, 'stale:': False, 'type:': 'release'}
```

As you can see in the picture below, the events for the same toggle, it doesn't update any of the fields. 
![Screenshot 2022-06-15 at 13 26 56](https://user-images.githubusercontent.com/81520864/173826624-0a0ec5c6-e80d-42c3-aa3f-2c289a8e3708.png)

For POST it returns multiple 409s. 
For PUT it returns multiple 200s.

**_SCRIPT_**
```
import requests
from google.cloud import storage
import json
from dotenv import load_dotenv
import os
from datetime import datetime
load_dotenv()

now = datetime.now().strftime("%d-%m-%y")
bucket_name = "development-unleash-backups"

client = storage.Client.from_service_account_json("restore/unleash-dev.json")
bucket = client.get_bucket('development-unleash-backups')
blob = bucket.get_blob(f"unleash-backup-{now}.json")
file_data = json.loads(blob.download_as_string())


API_KEY = "*:*.d518d2ffa43c849b5eff47a07180bf5f75554ee7ae1444af00372968"
server = "http://localhost:4242/api/"

headers = {
    "Authorization": f"{API_KEY}",
    "Content-Type": "application/json"
    }

with open('./test.json') as file:
    data = json.load(file)

for i in data['features']:
    toggles = {
        "name": i['name'],
        "description:": i['description'],
        "enabled:": i['enabled'],
        "stale:": i['stale'],
        "type:": i['type']
    }
    parameter = {
        "keep": "false"
    }

    url = server + f"admin/projects/default/features/{i['name']}"
    r = requests.put(url=url, headers=headers, json=toggles, params=parameter)
    print(r.status_code)
```

For POST I change the last 3 lines to the below
```
    url = server + f"admin/projects/default/features"
    r = requests.post(url=url, headers=headers, json=toggles, params=parameter)
    print(r.status_code)
```

**Comment by thomasheartman** [comment] 2022-06-28 14:17
I'll be closing this now because it seems to be solved. If you think there's more left to do, feel free to open it up again 😄

**Closed by thomasheartman** 2022-06-28 14:17 UTC
Labels: bug
