### ISSUE TITLE
Completely remove feature toggle

### ISSUE THREAD

**Issue by Muchaszewski** [Unleash/unleash#1802] opened 2022-07-11 11:14 UTC
### Describe the feature request

I would like to delete a feature toggle entirely after it has been archived.

### Background

1. Keep the archive clean of items that are no longer relevant. 
2. Allow for fixing the typos in the feature toggles names (can be a different feature but archive->remove->recreate sounds safe)
3. Encourage testing. Create a test toggle or setting for development and then remove it after you are done with it, especially operational would be usefull

### Solution suggestions

First, you should archive a feature toggle, then you should be able to remove it, or remove it after a specified amount of time so that we do not remove it while was being used and was considered active. 

Possible first mark it as stale, but this is not possible from the archive.

**Comment by chriswk** [comment] 2022-07-11 12:02
[This is already possible using the API](https://docs.getunleash.io/api/admin/features-archive#delete-an-archived-feature-toggle)

**Comment by Muchaszewski** [comment] 2022-07-11 12:04
Thank you, I have missed it somehow.

But can it be part of the UI? Thank you

**Comment by sheastyer** [comment] 2022-07-12 15:24
@chriswk Is the same possible for custom strategies? I know it is possible to deprecate them, haven't seen the same delete option anywhere in the documentation

**Comment by sighphyre** [comment] 2022-07-14 06:39
@Muchaszewski We historically haven't included this in the UI because it's quite a dangerous operation to do - the risk is that you accidentally turn off an ancient toggle that's been forgotten about. That being said, we've raised this to the design team and it sounds like we'll be adding this to the UI in the nearish future, it just needs a bit of thought so that we can make it as safe as we can and obvious that it's dangerous

(Exuse the label, it's just to keep our stale bot from closing this before we get to it)

**Comment by sighphyre** [comment] 2022-07-14 06:40
@sheastyer Unfortunately there isn't an equivalent endpoint for this, for similar reasons to the above and largely because it's even more dangerous, but i can raise this to the team and see if we can do something about it. If that's a feature you really need, would it be possible to open a separate issue for it?

**Comment by Muchaszewski** [comment] 2022-07-14 07:57
> @Muchaszewski We historically haven't included this in the UI because it's quite a dangerous operation to do - the risk is that you accidentally turn off an ancient toggle that's been forgotten about. That being said, we've raised this to the design team and it sounds like we'll be adding this to the UI in the nearish future, it just needs a bit of thought so that we can make it as safe as we can and obvious that it's dangerous
> 
> (Exuse the label, it's just to keep our stale bot from closing this before we get to it)

Absolutely that makes perfect sense. 

To add to this some ideas, when you remove ancient toggle that was critical to the operations of the application.

1. Shouldn't you see that it broke something from after you archive your toggle in the first place? 
2. If the toggle was already archived, and there were some important data stored, I would argue that they were not that important if the toggle was archived in the first place. To countermeasure accidents, I cannot check now, but there should be archive date so that everyone can see how long ago that toggle was archived.
3. I don't think this is possible right now, but what about preview of the toggle before removal. There is no UI to preview data of archived toggle. This could be useful. Or in terms of where the remove button should be located is after you open archived toggle for preview. Then you would see what you are removing, in terms of content and not only the label.
4. Removal from API is in my opinion more dangerous then from UI, because if someone takes some effort to make a script to remove toggles, then it would be probably a cron script to remove toggles older then X, and then everyone forget about it. And an accident is about to happen.

That's just a few of my concerns about the current approach and about the implementation of the button.

Thank you for working on it, my team would much appreciate!

**Comment by sighphyre** [comment] 2022-07-14 08:31
1) You probably should if you just delete an archived toggle. I think I've explained myself terribly here haha. If you have an archived toggle it'll block creation of a toggle with the same name, but if you remove it and accidentally create a toggle with the same name as the archived toggle that now got deleted, you might be turning on/off parts of the system you don't expect. I think there's definitely some things we can and should do to improve this though and I think this is super unclear to people using this at the moment
2) I think this is related to me explaining myself terribly but yes, an archived toggle shouldn't be important. I think you're right about the point here though, having the date in that would allow folks to tell the difference between a toggle that got archived long in the past and has been confirmed to be safe for proper clean up and a toggle that got archived yesterday
3) Another great idea, I'm going to take this to our design team!
4) That's a fair point, we already have a few users doing exactly this but mostly because they have way too many toggles to do this manually anyway. I think for a cases where you just want to clean up a few toggles, requiring human eyes and being clear about the risks is safer than scripts that potentially have bugs or are incorrectly designed

Thanks so much for your great inputs here, I'm going to take this whole thread to the team. We'll put an update here when we implement this

**Comment by sheastyer** [comment] 2022-07-14 16:11
> @sheastyer Unfortunately there isn't an equivalent endpoint for this, for similar reasons to the above and largely because it's even more dangerous, but i can raise this to the team and see if we can do something about it. If that's a feature you really need, would it be possible to open a separate issue for it?

@sighphyre I do want to clarify, it already seems like there is an option in the UI to 'delete' a custom strategy... just wondering if that is exposed via some sort of endpoint as well for terraform like migrations and rolling back that config.

**Comment by sheastyer** [comment] 2022-07-14 18:42
@sighphyre After going to the console and looking at network traffic - it looks like the UI hits `/api/admin/strategies/<name>` with DELETE method - though this is nowhere in the docs. Maybe I should open an issue to add that? I assume its not hidden on purpose due to the danger you mentioned since it is available on the UI. To confirm, I am clicking the 'trash' button on the `/strategies` page.

**Comment by sighphyre** [comment] 2022-07-15 06:36
@sheastyer Oh gosh, yeah, I was going off our docs in my response to you. That very much sounds like a documentation bug that we both got bitten by. 

Yes please, if you open an issue for that I'll send it our docs folks and get that patched

**Comment by sighphyre** [comment] 2022-07-28 12:27
Closed by https://github.com/Unleash/unleash-frontend/pull/1150

Should be out in the v4.14.0 release

**Closed by sighphyre** 2022-07-28 12:27 UTC
Labels: enhancement, new, Maybe Later
